package Brewtato;

import java.awt.*;
import java.awt.image.*;
import java.io.*;
import java.nio.*;
import java.util.*;
import java.util.List;

import static org.lwjgl.opengl.GL11.*;

public class TrueTypeFont {
    private String path;
    private Font font;
    private ByteBuffer imageData;
    private BufferedImage imageBuffer;
    private Graphics2D imageGraphics;
    private int image = 0;

    private static final Map<Integer, String> CHARS = new HashMap<>() {{
        put(1, "ABCDEFGHIJKLMNOPRSTUVWXYQZ");
        put(2, "abcdefhiklmnorstuvwxzgpqyj");
        put(3, "0123456789");
        put(5, "$+-*/=%\"'#@&_(),.;:?!\\|<>[]Ã,Â§`^~");
    }};

    public TrueTypeFont(String path) throws Exception {
        this.path = path;

        try {
            font = Font.createFont(java.awt.Font.TRUETYPE_FONT, new File(path)).deriveFont(32f);

            generateTexture();

        } catch (FontFormatException ex) {
            throw new Exception("Font is not a TTF!");
        } catch (IOException ex) {
            throw new Exception(ex);
        }
    }

    //Draws the bitmap generated by the class
    public void drawBitmap(float x, float y) {
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, image);
        glBegin(GL_QUADS);

        glTexCoord2f(0, 0);
        glVertex3f(x, y + 512, 0);

        glTexCoord2f(1, 0);
        glVertex3f(x + 512, y + 512, 0);

        glTexCoord2f(1, 1);
        glVertex3f(x + 512, y, 0);

        glTexCoord2f(0, 1);
        glVertex3f(x, y, 0);

        glEnd();
        glDisable(GL_TEXTURE_2D);
    }

    public void drawText(String text, float x, float y, float size) {
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, image);
        glBegin(GL_QUADS);
        Set<Character> lowercaseChars = new HashSet<>(Arrays.asList('p', 'q', 'j', 'g', 'y'));
        for (char c : text.toCharArray()) {
            for (int index : CHARS.keySet()) {
                float p = (float) CHARS.get(index).indexOf(c);
                if (p >= 0) {
                    float recY = 1f / 512f * 32f;
                    float recX = 1f / 512f * 16f;
                    float xStart = recX * p;
                    float yStart = recY * (index - 1);

                    float lowercase = 0;

                    if (lowercaseChars.contains(c)) {
                        lowercase += 1f / 512f * 4f;
                        recY += lowercase;
                        lowercase = 3f;
                    }





                    glTexCoord2f(xStart, yStart + recY);
                    glVertex3f(x, y - lowercase, 0);

                    glTexCoord2f(xStart + recX, yStart + recY);
                    glVertex3f(x + size, y - lowercase, 0);

                    glTexCoord2f(xStart + recX, yStart);
                    glVertex3f(x + size, y - lowercase + size * 2, 0);

                    glTexCoord2f(xStart, yStart);
                    glVertex3f(x, y - lowercase + size * 2, 0);

                    break;
                }
            }
            x += size;
        }

        glEnd();
        glDisable(GL_TEXTURE_2D);
    }

    public int stringWidth (String string, int size) {
        return size * string.length();
    }

    private void generateTexture() {

        glEnable(GL_TEXTURE_2D);

//Configure
        GraphicsConfiguration gc = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDefaultConfiguration();
        Graphics2D graphics = gc.createCompatibleImage(1, 1, Transparency.TRANSLUCENT).createGraphics();
        graphics.setFont(font);

        //Create the image buffer
        FontMetrics fontMetrics = graphics.getFontMetrics();
        BufferedImage imageBuffer = graphics.getDeviceConfiguration().createCompatibleImage(512, 512, Transparency.TRANSLUCENT);

//Draw the characters on our image
        imageGraphics = (Graphics2D) imageBuffer.getGraphics();
        imageGraphics.setFont(font);
        imageGraphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_OFF);
        imageGraphics.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

        // draw every CHAR by line...
        CHARS.keySet().stream().forEach(i -> {
            imageGraphics.setColor(Color.WHITE);
            imageGraphics.drawString(CHARS.get(i), 0, fontMetrics.getMaxAscent() * i);
        });


//Generate texture data
        int[] pixels = new int[imageBuffer.getWidth() * imageBuffer.getHeight()];
        imageBuffer.getRGB(0, 0, imageBuffer.getWidth(), imageBuffer.getHeight(), pixels, 0, imageBuffer.getWidth());
        imageData = ByteBuffer.allocateDirect((imageBuffer.getWidth() * imageBuffer.getHeight() * 4));

        for (int y = 0; y < imageBuffer.getHeight(); y++) {
            for (int x = 0; x < imageBuffer.getWidth(); x++) {
                int pixel = pixels[y * imageBuffer.getWidth() + x];
                imageData.put((byte) ((pixel >> 16) & 0xFF));     // Red component
                imageData.put((byte) ((pixel >> 8) & 0xFF));      // Green component
                imageData.put((byte) (pixel & 0xFF));               // Blue component
                imageData.put((byte) ((pixel >> 24) & 0xFF));    // Alpha component. Only for RGBA
            }
        }

        imageData.flip();

        //Generate texture
        image = glGenTextures();

        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, image);
        glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, 512, 512, 0, GL_RGBA, GL_UNSIGNED_BYTE, imageData);

        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
        glDisable(GL_TEXTURE_2D);
    }
}